Resources:
  collarQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "smart-dog-collar-app-test-collarQueue"
      ReceiveMessageWaitTimeSeconds: 10
      VisibilityTimeout: 90
  collarLoggerQueueFIFO:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: "smart-dog-collar-app-test-collarLoggerQueue.fifo"
      FifoQueue: true
      ContentBasedDeduplication: true
  dogCollarTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: "smart-dog-collar-app-test-snsTopic"