Resources:
  collarQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "smart-dog-collar-app-test-${self:provider.stage}-collarQueue"
      ReceiveMessageWaitTimeSeconds: 10
      VisibilityTimeout: 90
  collarLoggerQueueFIFO:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: "smart-dog-collar-app-test-${self:provider.stage}-collarLoggerQueue.fifo"
      FifoQueue: true
      ContentBasedDeduplication: true